// Code generated by MockGen. DO NOT EDIT.
// Source: TodoAPI/services (interfaces: TodoService)

// Package services is a generated GoMock package.
package services

import (
	models "TodoAPI/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockTodoService is a mock of TodoService interface.
type MockTodoService struct {
	ctrl     *gomock.Controller
	recorder *MockTodoServiceMockRecorder
}

// MockTodoServiceMockRecorder is the mock recorder for MockTodoService.
type MockTodoServiceMockRecorder struct {
	mock *MockTodoService
}

// NewMockTodoService creates a new mock instance.
func NewMockTodoService(ctrl *gomock.Controller) *MockTodoService {
	mock := &MockTodoService{ctrl: ctrl}
	mock.recorder = &MockTodoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoService) EXPECT() *MockTodoServiceMockRecorder {
	return m.recorder
}

// DeleteTodo mocks base method.
func (m *MockTodoService) DeleteTodo(arg0 primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoServiceMockRecorder) DeleteTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoService)(nil).DeleteTodo), arg0)
}

// GetTodo mocks base method.
func (m *MockTodoService) GetTodo() ([]models.TodoModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo")
	ret0, _ := ret[0].([]models.TodoModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoServiceMockRecorder) GetTodo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoService)(nil).GetTodo))
}

// PostTodo mocks base method.
func (m *MockTodoService) PostTodo(arg0 models.TodoModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostTodo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostTodo indicates an expected call of PostTodo.
func (mr *MockTodoServiceMockRecorder) PostTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTodo", reflect.TypeOf((*MockTodoService)(nil).PostTodo), arg0)
}
